#pragma once

// Generated by tools/generate_touch_activity_profiles.py.
// Fingerprints and verified bytecode local indices; no retail code is embedded.
#include <array>
#include <cstdint>
#include <string_view>
#include "input/context_touch_activity_types.h"

namespace gta4::input {
struct TouchActivityProfile {
  uint32_t episode, program_key, code_size, local_count;
  TouchActivityKind kind;
  std::string_view name, sha256;
  std::array<uint16_t, 8> locals;
};

inline constexpr std::array<TouchActivityProfile, 26> kTouchActivityProfiles{{
  {0, 0xF9F91D07u, 78866, 2153, TouchActivityKind::kBowling,
   "tenpinbowl", "ffea48ea78da16e13b51ae1f280194f61b30090ed5a8b76724b2ab3c3e496f51", {2145, 2146, 65535, 65535, 65535, 65535, 65535, 65535}},
  {0, 0x88123A9Cu, 72007, 761, TouchActivityKind::kPool,
   "pool_game", "201c4d15e748e4173ab8794fc25b3b23b317174a0666c34f638799e213f2f66b", {240, 241, 65535, 65535, 65535, 65535, 65535, 65535}},
  {0, 0x8E8E6AF8u, 39491, 426, TouchActivityKind::kDarts,
   "darts", "44c18ac934e2695da818a875a3033f2096a00dee863da6961701ed500c7a7d1e", {0, 1, 65535, 65535, 65535, 65535, 65535, 65535}},
  {0, 0x881750F6u, 56728, 1369, TouchActivityKind::kQub3d,
   "puzzle", "4e18b57814dd173920407511f386f12847cdfd83067b8603f11e44824cb7c4a2", {4, 5, 65535, 65535, 65535, 65535, 65535, 65535}},
  {0, 0xC703DB5Fu, 62483, 807, TouchActivityKind::kTaxi,
   "taxi", "bf1b0e542f9c6ae2fec540b25177e3bc45f1af9cbff5eb0f8822de26e9eb948e", {171, 172, 65535, 65535, 65535, 65535, 65535, 65535}},
  {0, 0xA2E0F8A4u, 58397, 775, TouchActivityKind::kPoliceComputer,
   "policetest", "70157a764bf6dc0e4fc821552776e169fa7f42340ca642152260bde3475451bf", {488, 492, 474, 65535, 65535, 65535, 65535, 65535}},
  {1, 0xF9F91D07u, 80975, 1283, TouchActivityKind::kBowling,
   "tenpinbowl", "24b15d0446ac368f9d9184df34d880f9fb01f134591c280e64ed1330c76e616f", {1275, 1276, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0x88123A9Cu, 72533, 731, TouchActivityKind::kPool,
   "pool_game", "e380f1fd74570edbd9ae8e6263f79ea82124a0662731c011a200161485fef799", {198, 199, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0x8E8E6AF8u, 40067, 437, TouchActivityKind::kDarts,
   "darts", "eae3fd3332dddc0e48334c5de3e9849c7c9fa9509e9bbf4870da0a29173750c7", {0, 1, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0x881750F6u, 56782, 1369, TouchActivityKind::kQub3d,
   "puzzle", "124f37e768d26983588a22d78e25e70241e515dcfadd4175512fd2d35a6f39bb", {4, 5, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0xC703DB5Fu, 49051, 807, TouchActivityKind::kTaxi,
   "taxi", "af71503a1768a0c2652db4cf9a12d6d9d5c85d3aecc54cf9603027d08268d92b", {171, 172, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0xA2E0F8A4u, 56941, 773, TouchActivityKind::kPoliceComputer,
   "policetest", "5024c9920c1099340c5a7bd301604b4ba05948409ab934ba4fa1d7de9c15a5e1", {486, 490, 472, 65535, 65535, 65535, 65535, 65535}},
  {2, 0xF9F91D07u, 78137, 1073, TouchActivityKind::kBowling,
   "tenpinbowl", "9fbc1ef4312538f4f28d2f5f5358a7303c716d6e370a6dcc82baf79e204f0e2d", {1065, 1066, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0x88123A9Cu, 72984, 731, TouchActivityKind::kPool,
   "pool_game", "913e63d06b007b852d298cb0c530ff4c538fd6db5df821d009cf62cfce54850d", {198, 199, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0x8E8E6AF8u, 40441, 438, TouchActivityKind::kDarts,
   "darts", "0c910c84a23d93b5045071627ea917521c598b96648718793e3f6dbc1ab97cb4", {2, 3, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0x881750F6u, 56782, 1369, TouchActivityKind::kQub3d,
   "puzzle", "b55252ffbad4d5e13f0b354eff9401806c0055923cdc217320e8b7826ba98e8f", {4, 5, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0xC703DB5Fu, 53411, 809, TouchActivityKind::kTaxi,
   "taxi", "c280bbd3c769a91ff92a999f7704cbaf44e3024414958ffeac84cd107883dd1c", {172, 173, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0xA2E0F8A4u, 44889, 773, TouchActivityKind::kPoliceComputer,
   "policetest", "469cb8a6df4a067508facf2edb4e7c9a26e7842c78cc3aab4d256bda7e80b3d8", {486, 490, 472, 65535, 65535, 65535, 65535, 65535}},
  {1, 0x98CD90D1u, 31895, 591, TouchActivityKind::kAirHockey,
   "air_hockey", "429d2cbe06a0e8ad61f551d9390590ae5aaca89151c8107cd6fa4c1467599869", {241, 518, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0x98CD90D1u, 31728, 478, TouchActivityKind::kAirHockey,
   "air_hockey", "21f20855447d8609698bd22a4b220e6d6ffb69e0e8a91083a8924b9cc169c597", {128, 405, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0xF0B99C59u, 39657, 310, TouchActivityKind::kArmWrestling,
   "arm_wrestling", "026bd675c7e880b9ac61f4d9a6251289817013ae3d4a2c8671a1a171707f16df", {182, 184, 65535, 65535, 65535, 65535, 65535, 65535}},
  {1, 0x1597C3BDu, 44531, 370, TouchActivityKind::kHiLo,
   "hi_lo_cards", "e014b179a4f332c11281e78d85d97fa125619a385c666e2162f9941c1d32da3e", {155, 212, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0x87E51030u, 118575, 681, TouchActivityKind::kDancing,
   "dancing", "c6a93c7897f8b1142ffe942173e5d97b248f857158818433f2cc90e9de693870", {247, 248, 65535, 65535, 65535, 65535, 65535, 65535}},
  {2, 0xDE14822Eu, 86246, 724, TouchActivityKind::kChampagne,
   "drinking", "ff062cfa6cf95afbb37e80c81f4f6d8fe456b1523df910e1827c61c57bdd6e2d", {272, 274, 443, 603, 498, 497, 496, 453}},
  {2, 0x299717F2u, 30503, 3146, TouchActivityKind::kGolf,
   "golf", "ffd3ac3bcc16fab5dd311a760cf9b3196b897f16d0a6eddc60281de1f070def7", {3136, 3139, 2893, 3141, 65535, 65535, 65535, 65535}},
  {2, 0x7CEB8820u, 56100, 1408, TouchActivityKind::kCageFighting,
   "fightclubring", "c8ae6142630a2013348b45e35b8d37ebcd8f2dbf60b743571660c8d283e510b2", {961, 1131, 65535, 65535, 65535, 65535, 65535, 65535}},
}};

}  // namespace gta4::input
