// Differential execution of the unmodified production resolve shader.
#include "native_vulkan_test_context.h"
#include "graphics/gta4_native/native_resolve_reuse.h"
#include <fstream>
#include <filesystem>
#include <limits>
#include <cmath>
using namespace liberty::test;
using namespace rex::graphics::gta4_native;
namespace {
constexpr uint32_t W=64,H=48;constexpr size_t bytes=size_t(W)*H*8;
struct Constants {
 int32_t source_origin[2]{},destination_origin[2]{};
 uint32_t source_samples{},requested_samples{},destination_samples{},select{},mode{},physical_source{},physical_destination{},flags{1};
 uint32_t source_extent[2]{W,H},destination_extent[2]{W,H};
};
static_assert(sizeof(Constants)==64);
struct Fixture {
 Context& c;Image source;std::array<Image,3> targets;Buffer upload,download;
 VkImageView source_view{};std::array<VkImageView,3> views{};VkSampler sampler{};VkDescriptorSetLayout dl{};VkDescriptorPool dp{};VkDescriptorSet ds{};VkPipelineLayout pl{};
 VkShaderModule vert{},frag{},fused{};std::array<VkRenderPass,2> passes{};std::array<VkPipeline,2> pipelines{};std::array<VkFramebuffer,3> framebuffers{};
 VkImageView View(Image im,VkFormat format){VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=im.image;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=format;vi.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};VkImageView view;V(vkCreateImageView(c.device,&vi,nullptr,&view));return view;}
 VkShaderModule Shader(const std::filesystem::path& file){std::ifstream f(file,std::ios::binary|std::ios::ate);Check(bool(f),"shader open");size_t n=size_t(f.tellg());Check(n&&n%4==0,"shader size");std::vector<uint32_t> data(n/4);f.seekg(0);f.read((char*)data.data(),n);Check(bool(f),"shader read");VkShaderModuleCreateInfo si{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};si.codeSize=n;si.pCode=data.data();VkShaderModule m;V(vkCreateShaderModule(c.device,&si,nullptr,&m));return m;}
 Fixture(Context& context,const std::filesystem::path& directory):c(context),source(c.NewImage(VK_FORMAT_R32G32B32A32_SFLOAT,W,H,VK_IMAGE_USAGE_SAMPLED_BIT)),targets{c.NewImage(VK_FORMAT_R16G16B16A16_SFLOAT,W,H,VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT),c.NewImage(VK_FORMAT_R16G16B16A16_SFLOAT,W,H,VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT),c.NewImage(VK_FORMAT_R16G16B16A16_SFLOAT,W,H,VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT)},upload(c.NewBuffer(W*H*16,false)),download(c.NewBuffer(bytes*3,false)){
  source_view=View(source,VK_FORMAT_R32G32B32A32_SFLOAT);for(size_t i=0;i<3;++i)views[i]=View(targets[i],VK_FORMAT_R16G16B16A16_SFLOAT);
  VkSamplerCreateInfo sc{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};sc.magFilter=sc.minFilter=VK_FILTER_NEAREST;sc.mipmapMode=VK_SAMPLER_MIPMAP_MODE_NEAREST;sc.addressModeU=sc.addressModeV=sc.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;V(vkCreateSampler(c.device,&sc,nullptr,&sampler));
  VkDescriptorSetLayoutBinding binding{0,VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1,VK_SHADER_STAGE_FRAGMENT_BIT,nullptr};VkDescriptorSetLayoutCreateInfo lc{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};lc.bindingCount=1;lc.pBindings=&binding;V(vkCreateDescriptorSetLayout(c.device,&lc,nullptr,&dl));VkDescriptorPoolSize size{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1};VkDescriptorPoolCreateInfo pc{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};pc.maxSets=1;pc.poolSizeCount=1;pc.pPoolSizes=&size;V(vkCreateDescriptorPool(c.device,&pc,nullptr,&dp));VkDescriptorSetAllocateInfo da{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};da.descriptorPool=dp;da.descriptorSetCount=1;da.pSetLayouts=&dl;V(vkAllocateDescriptorSets(c.device,&da,&ds));VkDescriptorImageInfo di{sampler,source_view,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};VkWriteDescriptorSet dw{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};dw.dstSet=ds;dw.descriptorCount=1;dw.descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;dw.pImageInfo=&di;vkUpdateDescriptorSets(c.device,1,&dw,0,nullptr);
  VkPushConstantRange push{VK_SHADER_STAGE_FRAGMENT_BIT,0,sizeof(Constants)};VkPipelineLayoutCreateInfo plc{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};plc.setLayoutCount=1;plc.pSetLayouts=&dl;plc.pushConstantRangeCount=1;plc.pPushConstantRanges=&push;V(vkCreatePipelineLayout(c.device,&plc,nullptr,&pl));
  vert=Shader(directory/"fullscreen.vert.spv");frag=Shader(directory/"resolve.frag.spv");fused=Shader(directory/"resolve-fused.frag.spv");
  for(uint32_t n=1;n<=2;++n){std::array<VkAttachmentDescription,2> attachments{};std::array<VkAttachmentReference,2> refs{};for(uint32_t i=0;i<n;++i){auto&a=attachments[i];a.format=VK_FORMAT_R16G16B16A16_SFLOAT;a.samples=VK_SAMPLE_COUNT_1_BIT;a.loadOp=VK_ATTACHMENT_LOAD_OP_LOAD;a.storeOp=VK_ATTACHMENT_STORE_OP_STORE;a.initialLayout=VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;a.finalLayout=VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;refs[i]={i,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};}
   VkSubpassDescription sub{};sub.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sub.colorAttachmentCount=n;sub.pColorAttachments=refs.data();VkRenderPassCreateInfo ri{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};ri.attachmentCount=n;ri.pAttachments=attachments.data();ri.subpassCount=1;ri.pSubpasses=&sub;V(vkCreateRenderPass(c.device,&ri,nullptr,&passes[n-1]));
   std::array<VkPipelineShaderStageCreateInfo,2> stages{};for(auto&st:stages){st.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;st.pName="main";}stages[0].stage=VK_SHADER_STAGE_VERTEX_BIT;stages[0].module=vert;stages[1].stage=VK_SHADER_STAGE_FRAGMENT_BIT;stages[1].module=n==2?fused:frag;
   VkPipelineVertexInputStateCreateInfo vi{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};ia.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;VkViewport vp{0,0,float(W),float(H),0,1};VkRect2D rect{{0,0},{W,H}};VkPipelineViewportStateCreateInfo vs{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};vs.viewportCount=vs.scissorCount=1;vs.pViewports=&vp;vs.pScissors=&rect;VkPipelineRasterizationStateCreateInfo rs{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};rs.polygonMode=VK_POLYGON_MODE_FILL;rs.cullMode=VK_CULL_MODE_NONE;rs.lineWidth=1;VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};ms.rasterizationSamples=VK_SAMPLE_COUNT_1_BIT;
   std::array<VkPipelineColorBlendAttachmentState,2> ba{};for(auto&b:ba)b.colorWriteMask=15;VkPipelineColorBlendStateCreateInfo bs{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};bs.attachmentCount=n;bs.pAttachments=ba.data();VkDynamicState dynamic=VK_DYNAMIC_STATE_SCISSOR;VkPipelineDynamicStateCreateInfo dy{VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};dy.dynamicStateCount=1;dy.pDynamicStates=&dynamic;VkGraphicsPipelineCreateInfo pi{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};pi.stageCount=2;pi.pStages=stages.data();pi.pVertexInputState=&vi;pi.pInputAssemblyState=&ia;pi.pViewportState=&vs;pi.pRasterizationState=&rs;pi.pMultisampleState=&ms;pi.pColorBlendState=&bs;pi.pDynamicState=&dy;pi.layout=pl;pi.renderPass=passes[n-1];V(vkCreateGraphicsPipelines(c.device,VK_NULL_HANDLE,1,&pi,nullptr,&pipelines[n-1]));
  }
  for(size_t i=0;i<3;++i){VkFramebufferCreateInfo fi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fi.renderPass=passes[i==2?1:0];fi.attachmentCount=i==2?2:1;fi.pAttachments=i==2?views.data()+1:views.data()+i;fi.width=W;fi.height=H;fi.layers=1;V(vkCreateFramebuffer(c.device,&fi,nullptr,&framebuffers[i]));}
 }
 void Barrier(VkCommandBuffer cb,Image& im,VkImageLayout to){VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.oldLayout=im.layout;b.newLayout=to;b.srcQueueFamilyIndex=b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=im.image;b.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};b.srcAccessMask=im.layout==VK_IMAGE_LAYOUT_UNDEFINED?0:VK_ACCESS_MEMORY_READ_BIT|VK_ACCESS_MEMORY_WRITE_BIT;b.dstAccessMask=VK_ACCESS_MEMORY_READ_BIT|VK_ACCESS_MEMORY_WRITE_BIT;vkCmdPipelineBarrier(cb,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,0,0,nullptr,0,nullptr,1,&b);im.layout=to;}
 void Input(uint32_t mode){auto*p=(float*)upload.data;for(size_t i=0;i<W*H*4;++i){float v=float(int((i*31+mode*13)%2000)-500)/32.0f;if(mode%4==3){if(i%71==0)v=std::numeric_limits<float>::infinity();if(i%73==0)v=-std::numeric_limits<float>::infinity();if(i%79==0)v=std::numeric_limits<float>::quiet_NaN();if(i%83==0)v=100000.f;}p[i]=v;}}
 void Upload(VkCommandBuffer cb){Barrier(cb,source,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);VkBufferImageCopy cp{};cp.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};cp.imageExtent={W,H,1};vkCmdCopyBufferToImage(cb,upload.buffer,source.image,source.layout,1,&cp);Barrier(cb,source,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);}
 void InitTargets(VkCommandBuffer cb){for(auto&t:targets){Barrier(cb,t,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);VkClearColorValue clear{{7,7,7,7}};VkImageSubresourceRange range{VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkCmdClearColorImage(cb,t.image,t.layout,&clear,1,&range);Barrier(cb,t,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);}}
 void Draw(VkCommandBuffer cb,uint32_t target,const Constants& constants,bool mirror=false){Barrier(cb,targets[target],VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);if(mirror)Barrier(cb,targets[2],VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);VkRenderPassBeginInfo bi{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};bi.renderPass=passes[mirror?1:0];bi.framebuffer=framebuffers[mirror?2:target];bi.renderArea.extent={W,H};vkCmdBeginRenderPass(cb,&bi,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(cb,VK_PIPELINE_BIND_POINT_GRAPHICS,pipelines[mirror?1:0]);vkCmdBindDescriptorSets(cb,VK_PIPELINE_BIND_POINT_GRAPHICS,pl,0,1,&ds,0,nullptr);VkRect2D rect{{constants.destination_origin[0],constants.destination_origin[1]},{constants.destination_extent[0],constants.destination_extent[1]}};vkCmdSetScissor(cb,0,1,&rect);vkCmdPushConstants(cb,pl,VK_SHADER_STAGE_FRAGMENT_BIT,0,sizeof(constants),&constants);vkCmdDraw(cb,3,1,0,0);vkCmdEndRenderPass(cb);}
 void Readback(VkCommandBuffer cb){for(size_t i=0;i<3;++i){Barrier(cb,targets[i],VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);VkBufferImageCopy cp{};cp.bufferOffset=bytes*i;cp.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};cp.imageExtent={W,H,1};vkCmdCopyImageToBuffer(cb,targets[i].image,targets[i].layout,download.buffer,1,&cp);}VkBufferMemoryBarrier host{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER};host.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;host.dstAccessMask=VK_ACCESS_HOST_READ_BIT;host.srcQueueFamilyIndex=host.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;host.buffer=download.buffer;host.size=bytes*3;vkCmdPipelineBarrier(cb,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,0,nullptr,1,&host,0,nullptr);}
 void Run(){uint32_t skipped=0;for(uint32_t test=0;test<96;++test){Input(test);auto cb=c.Begin(1);Upload(cb);InitTargets(cb);Constants pc;pc.flags=1u|((uint32_t(int(test%5)-2)&63u)<<8);bool partial=test%2;bool scaled=test%3==0;pc.select=test%7;
    if(partial){pc.source_origin[0]=1;pc.source_origin[1]=2;pc.destination_origin[0]=3;pc.destination_origin[1]=4;pc.source_extent[0]=pc.destination_extent[0]=32;pc.source_extent[1]=pc.destination_extent[1]=24;}
    if(scaled){pc.flags|=4;pc.destination_extent[0]/=2;pc.destination_extent[1]/=2;}
    NativeResolveReuseKey key{.recording=test+1,.source_image=2,.source_view=3,.source_lifetime=4,.source_writer=5,.destination_image=6,.destination_lifetime=7,.destination_generation=8,.operation=3,.source_format=109,.destination_format=97,.physical_samples=1};
    key.sample_select=pc.select;key.flags=pc.flags;key.exponent=int(test%5)-2;key.source_extent={pc.source_extent[0],pc.source_extent[1]};key.destination_extent={pc.destination_extent[0],pc.destination_extent[1]};key.source_origin={pc.source_origin[0],pc.source_origin[1]};key.destination_origin={pc.destination_origin[0],pc.destination_origin[1]};key.source_image_extent={W,H};key.destination_image_extent={W,H};
    Draw(cb,0,pc);Draw(cb,0,pc); // Reference performs the duplicated operation.
    Draw(cb,1,pc,true);NativeResolveReuseRecord memo;memo.Commit(key,1);Check(memo.Matches(key,1),"same operation must reuse");++skipped;
    Readback(cb);c.Wait(c.Submit(1,cb));auto*p=(uint8_t*)download.data;Check(std::memcmp(p,p+bytes,bytes)==0,"skipped resolve differs from repeated resolve");Check(std::memcmp(p+bytes,p+bytes*2,bytes)==0,"FP16 mirror differs from ordinary FP16 output");
    auto*h=(uint16_t*)download.data;for(uint32_t y=0;y<H;++y)for(uint32_t x=0;x<W;++x){bool inside=x>=uint32_t(pc.destination_origin[0])&&x<uint32_t(pc.destination_origin[0])+pc.destination_extent[0]&&y>=uint32_t(pc.destination_origin[1])&&y<uint32_t(pc.destination_origin[1])+pc.destination_extent[1];for(size_t ch=0;ch<4;++ch){uint16_t v=h[(y*W+x)*4+ch];if(!inside)Check(v==0x4700,"untouched region not preserved");else Check((v&0x7c00)!=0x7c00,"non-finite FP16 escaped sanitation");}}
   }
   std::cout<<"RESOLVE cases=96 duplicate_skips="<<skipped<<" outputs=bit-identical partial_guards=true mirror=bit-identical\n";
 }
 ~Fixture(){vkDeviceWaitIdle(c.device);for(auto f:framebuffers)vkDestroyFramebuffer(c.device,f,nullptr);for(auto p:pipelines)vkDestroyPipeline(c.device,p,nullptr);for(auto p:passes)vkDestroyRenderPass(c.device,p,nullptr);vkDestroyShaderModule(c.device,vert,nullptr);vkDestroyShaderModule(c.device,frag,nullptr);vkDestroyShaderModule(c.device,fused,nullptr);vkDestroyPipelineLayout(c.device,pl,nullptr);vkDestroyDescriptorPool(c.device,dp,nullptr);vkDestroyDescriptorSetLayout(c.device,dl,nullptr);vkDestroySampler(c.device,sampler,nullptr);for(auto v:views)vkDestroyImageView(c.device,v,nullptr);vkDestroyImageView(c.device,source_view,nullptr);}
};
}
int main(int argc,char**argv){try{Check(argc>=2,"shader directory required");{Context c(argc>2);Fixture f(c,argv[1]);f.Run();}Check(errors==0,"Vulkan validation errors");std::cout<<"PASS checks="<<checks<<" validation_errors="<<errors.load()<<'\n';return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
