// Spatial GPU replay and paired timing of stock/candidate postfx modules.
// Runs independently of the game and does not modify production shader caches.
#include <vulkan/vulkan.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>
#include <vector>
#include <bit>
#include <cstdlib>
#include "graphics/gta4_native/native_color_output_spirv.h"
#include "graphics/gta4_native/native_spirv_reflection.h"
using namespace rex::graphics::gta4_native;
namespace {
void Check(bool condition,const std::string& why){if(!condition)throw std::runtime_error(why);}
void V(VkResult result){Check(result==VK_SUCCESS,"Vulkan result "+std::to_string(result));}
std::vector<uint8_t> Read(const std::string& path){std::ifstream f(path,std::ios::binary|std::ios::ate);Check(bool(f),"open "+path);auto n=f.tellg();Check(n>=0&&n<64*1024*1024,"file size");std::vector<uint8_t>b(size_t(n),uint8_t{});f.seekg(0);f.read((char*)b.data(),n);Check(bool(f),"read "+path);return b;}
std::vector<uint32_t> Spirv(const std::string& path){auto b=Read(path);Check(b.size()%4==0,"SPIR-V length");std::vector<uint32_t>w(b.size()/4);std::memcpy(w.data(),b.data(),b.size());return w;}
std::string Entry(const std::vector<uint32_t>&w){for(size_t p=5;p<w.size();){auto n=w[p]>>16;Check(n&&n<=w.size()-p,"SPIR-V framing");if((w[p]&65535)==15){Check(n>=4,"entry framing");return std::string((const char*)&w[p+3],strnlen((const char*)&w[p+3],(n-3)*4));}p+=n;}throw std::runtime_error("entry missing");}
struct Buffer{VkBuffer handle{};VkDeviceMemory memory{};void* mapping{};VkDeviceAddress address{};};
struct Image{VkImage handle{};VkDeviceMemory memory{};VkImageView view{};uint32_t width{},height{},mip_levels{1};};
}
int main(int argc,char**argv){try{
 Check(argc==7,"usage: postfx_replay fullscreen.vert.spv cases.tsv output-directory width height repeats");
 const uint32_t width=uint32_t(std::stoul(argv[4])),height=uint32_t(std::stoul(argv[5])),repeats=uint32_t(std::stoul(argv[6]));
 Check(width>0&&width<=4096&&height>0&&height<=4096&&repeats>0&&repeats<=64,"bounded dimensions/repeats");
 std::filesystem::path output(argv[3]);std::filesystem::create_directories(output);
 VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.apiVersion=VK_API_VERSION_1_2;app.pApplicationName="Liberty material-shader verification";
 VkInstanceCreateInfo ii{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ii.pApplicationInfo=&app;VkInstance instance;V(vkCreateInstance(&ii,nullptr,&instance));
 uint32_t n=0;V(vkEnumeratePhysicalDevices(instance,&n,nullptr));Check(n>0,"no GPU");std::vector<VkPhysicalDevice> physicals(n);V(vkEnumeratePhysicalDevices(instance,&n,physicals.data()));auto physical=physicals[0];
 VkPhysicalDeviceProperties props{};vkGetPhysicalDeviceProperties(physical,&props);std::cout<<"GPU "<<props.deviceName<<'\n';
 VkPhysicalDeviceVulkan12Features f12{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES};VkPhysicalDeviceFeatures2 f2{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2};f2.pNext=&f12;vkGetPhysicalDeviceFeatures2(physical,&f2);
 Check(f12.bufferDeviceAddress&&f12.runtimeDescriptorArray,"BDA/runtime descriptor arrays unavailable");
 VkPhysicalDeviceVulkan12Features enable{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES};enable.bufferDeviceAddress=VK_TRUE;enable.runtimeDescriptorArray=VK_TRUE;enable.descriptorIndexing=f12.descriptorIndexing;enable.shaderSampledImageArrayNonUniformIndexing=f12.shaderSampledImageArrayNonUniformIndexing;
 VkPhysicalDeviceFeatures features{};features.shaderInt64=f2.features.shaderInt64;features.shaderSampledImageArrayDynamicIndexing=f2.features.shaderSampledImageArrayDynamicIndexing;features.independentBlend=f2.features.independentBlend;
 vkGetPhysicalDeviceQueueFamilyProperties(physical,&n,nullptr);std::vector<VkQueueFamilyProperties>qp(n);vkGetPhysicalDeviceQueueFamilyProperties(physical,&n,qp.data());uint32_t family=0;for(;family<n;++family)if(qp[family].queueFlags&VK_QUEUE_GRAPHICS_BIT)break;Check(family<n,"graphics queue");
 float priority=1;VkDeviceQueueCreateInfo qi{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qi.queueFamilyIndex=family;qi.queueCount=1;qi.pQueuePriorities=&priority;
 V(vkEnumerateDeviceExtensionProperties(physical,nullptr,&n,nullptr));std::vector<VkExtensionProperties>ex(n);V(vkEnumerateDeviceExtensionProperties(physical,nullptr,&n,ex.data()));std::vector<const char*>extensions;for(auto&e:ex)if(!std::strcmp(e.extensionName,"VK_KHR_portability_subset"))extensions.push_back("VK_KHR_portability_subset");
 VkDeviceCreateInfo di{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};di.pNext=&enable;di.pEnabledFeatures=&features;di.queueCreateInfoCount=1;di.pQueueCreateInfos=&qi;di.enabledExtensionCount=uint32_t(extensions.size());di.ppEnabledExtensionNames=extensions.data();VkDevice device;V(vkCreateDevice(physical,&di,nullptr,&device));VkQueue queue;vkGetDeviceQueue(device,family,0,&queue);
 VkPhysicalDeviceMemoryProperties mem{};vkGetPhysicalDeviceMemoryProperties(physical,&mem);auto memory_type=[&](uint32_t bits,uint32_t required){for(uint32_t i=0;i<mem.memoryTypeCount;++i)if((bits&(1u<<i))&&(mem.memoryTypes[i].propertyFlags&required)==required)return i;throw std::runtime_error("memory type");};
 std::vector<Buffer> buffers;
 auto buffer=[&](VkDeviceSize size,VkBufferUsageFlags usage,bool address){Buffer b;VkBufferCreateInfo ci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};ci.size=size;ci.usage=usage;V(vkCreateBuffer(device,&ci,nullptr,&b.handle));VkMemoryRequirements req;vkGetBufferMemoryRequirements(device,b.handle,&req);VkMemoryAllocateFlagsInfo flags{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO};flags.flags=VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.pNext=address?&flags:nullptr;ai.allocationSize=req.size;ai.memoryTypeIndex=memory_type(req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);V(vkAllocateMemory(device,&ai,nullptr,&b.memory));V(vkBindBufferMemory(device,b.handle,b.memory,0));V(vkMapMemory(device,b.memory,0,size,0,&b.mapping));if(address){VkBufferDeviceAddressInfo a{VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO};a.buffer=b.handle;b.address=vkGetBufferDeviceAddress(device,&a);}buffers.push_back(b);return b;};
 constexpr uint32_t layers=1,slots=32;
 Check(qp[family].timestampValidBits>0,"GPU timestamps unavailable");
 std::cout<<"DEVICE queue_count="<<qp[family].queueCount<<" timestamp_period_ns="<<props.limits.timestampPeriod<<" valid_bits="<<qp[family].timestampValidBits<<" width="<<width<<" height="<<height<<" repeats="<<repeats<<"\n";
 VkQueryPoolCreateInfo query_info{VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO};query_info.queryType=VK_QUERY_TYPE_TIMESTAMP;query_info.queryCount=repeats*2;VkQueryPool timestamps{};V(vkCreateQueryPool(device,&query_info,nullptr,&timestamps));
 auto shared=buffer(0x420,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,true);auto constants=buffer(4096,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,true);auto varyings=buffer(16*16,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,true);auto readback=buffer(width*height*16*layers,VK_BUFFER_USAGE_TRANSFER_DST_BIT,false);
 std::array<uint64_t,3> push{varyings.address,constants.address,shared.address};
 std::vector<Image> images;
 auto image=[&](uint32_t w,uint32_t h,VkImageUsageFlags usage,VkFormat format=VK_FORMAT_R32G32B32A32_SFLOAT,uint32_t levels=1){Image r;r.width=w;r.height=h;r.mip_levels=levels;VkImageCreateInfo ci{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ci.imageType=VK_IMAGE_TYPE_2D;ci.format=format;ci.extent={w,h,1};ci.mipLevels=levels;ci.arrayLayers=1;ci.samples=VK_SAMPLE_COUNT_1_BIT;ci.tiling=VK_IMAGE_TILING_OPTIMAL;ci.usage=usage;V(vkCreateImage(device,&ci,nullptr,&r.handle));VkMemoryRequirements req;vkGetImageMemoryRequirements(device,r.handle,&req);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=req.size;ai.memoryTypeIndex=memory_type(req.memoryTypeBits,0);V(vkAllocateMemory(device,&ai,nullptr,&r.memory));V(vkBindImageMemory(device,r.handle,r.memory,0));VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=r.handle;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=ci.format;vi.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,levels,0,1};V(vkCreateImageView(device,&vi,nullptr,&r.view));images.push_back(r);return r;};
 std::array<Image,slots> textures;
 std::array<size_t,slots> texture_offsets{};size_t upload_bytes=0;
 uint32_t requested_mips=std::getenv("REX_POSTFX_REPLAY_MIPS")?uint32_t(std::stoul(std::getenv("REX_POSTFX_REPLAY_MIPS"))):1u;Check(requested_mips>0&&requested_mips<=4,"bounded mip count");
 for(uint32_t i=0;i<slots;++i){texture_offsets[i]=upload_bytes;auto w=i<7?width:1u,h=i<7?height:1u;textures[i]=image(w,h,VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_TRANSFER_DST_BIT,VK_FORMAT_R16G16B16A16_SFLOAT,std::min(requested_mips,uint32_t(std::bit_width(std::min(w,h)))));for(uint32_t level=0;level<textures[i].mip_levels;++level)upload_bytes+=size_t(std::max(1u,w>>level))*std::max(1u,h>>level)*8;}
 auto texture_upload=buffer(upload_bytes,VK_BUFFER_USAGE_TRANSFER_SRC_BIT,false);
 std::array<Image,layers> targets;for(auto&t:targets)t=image(width,height,VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT);
 VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};si.magFilter=si.minFilter=VK_FILTER_NEAREST;si.mipmapMode=VK_SAMPLER_MIPMAP_MODE_NEAREST;si.addressModeU=si.addressModeV=si.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;si.maxLod=float(requested_mips-1);VkSampler sampler;V(vkCreateSampler(device,&si,nullptr,&sampler));
 si.magFilter=si.minFilter=VK_FILTER_LINEAR;si.mipmapMode=VK_SAMPLER_MIPMAP_MODE_LINEAR;VkSampler linear_sampler;V(vkCreateSampler(device,&si,nullptr,&linear_sampler));
 std::array<VkDescriptorSetLayout,5>layouts{};for(uint32_t i=0;i<layouts.size();++i){VkDescriptorSetLayoutBinding binding{};binding.binding=0;binding.descriptorCount=slots;binding.descriptorType=i==4?VK_DESCRIPTOR_TYPE_SAMPLER:VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;binding.stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT;VkDescriptorSetLayoutCreateInfo ci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};ci.bindingCount=(i==0||i==4)?1:0;ci.pBindings=&binding;V(vkCreateDescriptorSetLayout(device,&ci,nullptr,&layouts[i]));}
 std::array<VkDescriptorPoolSize,2>sizes{{{VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,slots},{VK_DESCRIPTOR_TYPE_SAMPLER,slots}}};VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=5;dpi.poolSizeCount=uint32_t(sizes.size());dpi.pPoolSizes=sizes.data();VkDescriptorPool dp;V(vkCreateDescriptorPool(device,&dpi,nullptr,&dp));std::array<VkDescriptorSet,5>sets{};VkDescriptorSetAllocateInfo da{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};da.descriptorPool=dp;da.descriptorSetCount=uint32_t(layouts.size());da.pSetLayouts=layouts.data();V(vkAllocateDescriptorSets(device,&da,sets.data()));
 std::array<VkDescriptorImageInfo,slots>ti{},sa{};for(uint32_t i=0;i<slots;++i){ti[i]={VK_NULL_HANDLE,textures[i].view,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};sa[i]={sampler,VK_NULL_HANDLE,VK_IMAGE_LAYOUT_UNDEFINED};}std::array<VkWriteDescriptorSet,2>writes{};for(auto&w:writes)w.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;writes[0].dstSet=sets[0];writes[0].descriptorType=VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE;writes[0].descriptorCount=slots;writes[0].pImageInfo=ti.data();writes[1].dstSet=sets[4];writes[1].descriptorType=VK_DESCRIPTOR_TYPE_SAMPLER;writes[1].descriptorCount=slots;writes[1].pImageInfo=sa.data();vkUpdateDescriptorSets(device,uint32_t(writes.size()),writes.data(),0,nullptr);
 VkPushConstantRange pr{VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,24};VkPipelineLayoutCreateInfo pli{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pli.setLayoutCount=uint32_t(layouts.size());pli.pSetLayouts=layouts.data();pli.pushConstantRangeCount=1;pli.pPushConstantRanges=&pr;VkPipelineLayout pl;V(vkCreatePipelineLayout(device,&pli,nullptr,&pl));
 std::array<VkAttachmentDescription,layers>adesc{};std::array<VkAttachmentReference,layers>refs{};std::array<VkImageView,layers>views{};for(uint32_t i=0;i<layers;++i){auto&a=adesc[i];a.format=VK_FORMAT_R32G32B32A32_SFLOAT;a.samples=VK_SAMPLE_COUNT_1_BIT;a.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;a.storeOp=VK_ATTACHMENT_STORE_OP_STORE;a.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;a.finalLayout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;refs[i]={i,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};views[i]=targets[i].view;}
 VkSubpassDescription sub{};sub.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sub.colorAttachmentCount=layers;sub.pColorAttachments=refs.data();VkSubpassDependency dep{};dep.srcSubpass=0;dep.dstSubpass=VK_SUBPASS_EXTERNAL;dep.srcStageMask=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;dep.dstStageMask=VK_PIPELINE_STAGE_TRANSFER_BIT;dep.srcAccessMask=VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;dep.dstAccessMask=VK_ACCESS_TRANSFER_READ_BIT;VkRenderPassCreateInfo ri{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};ri.attachmentCount=layers;ri.pAttachments=adesc.data();ri.subpassCount=1;ri.pSubpasses=&sub;ri.dependencyCount=1;ri.pDependencies=&dep;VkRenderPass rp;V(vkCreateRenderPass(device,&ri,nullptr,&rp));
 VkFramebufferCreateInfo fi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fi.renderPass=rp;fi.attachmentCount=layers;fi.pAttachments=views.data();fi.width=width;fi.height=height;fi.layers=1;VkFramebuffer fb;V(vkCreateFramebuffer(device,&fi,nullptr,&fb));
 VkCommandPoolCreateInfo pci{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};pci.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;pci.queueFamilyIndex=family;VkCommandPool pool;V(vkCreateCommandPool(device,&pci,nullptr,&pool));VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};cai.commandPool=pool;cai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;cai.commandBufferCount=1;VkCommandBuffer cb;V(vkAllocateCommandBuffers(device,&cai,&cb));
 auto module=[&](const std::vector<uint32_t>&w){VkShaderModuleCreateInfo ci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};ci.codeSize=w.size()*4;ci.pCode=w.data();VkShaderModule m;V(vkCreateShaderModule(device,&ci,nullptr,&m));return m;};auto vw=Spirv(argv[1]);auto vm=module(vw);auto ventry=Entry(vw);
 std::map<std::string,VkPipeline>pipelines;std::vector<VkShaderModule>modules{vm};
 auto pipeline=[&](const std::string&path,uint32_t spec){auto key=path+":"+std::to_string(spec);if(pipelines.contains(key))return pipelines[key];auto words=Spirv(path);if(std::getenv("REX_POSTFX_REPLAY_NATIVE_OUTPUT")){auto transformed=AddNativeColorOutputEpilogue(words);Check(bool(transformed),"native output epilogue");words=std::move(*transformed);}auto output_mask=ReflectNativeFragmentColorOutputMask(words);Check(bool(output_mask),"reflect output mask");auto fm=module(words);modules.push_back(fm);auto entry=Entry(words);VkSpecializationMapEntry map{0,0,4};VkSpecializationInfo specialization{1,&map,4,&spec};std::array<VkPipelineShaderStageCreateInfo,2>stages{};for(auto&s:stages)s.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;stages[0].stage=VK_SHADER_STAGE_VERTEX_BIT;stages[0].module=vm;stages[0].pName=ventry.c_str();stages[1].stage=VK_SHADER_STAGE_FRAGMENT_BIT;stages[1].module=fm;stages[1].pName=entry.c_str();stages[1].pSpecializationInfo=&specialization;VkPipelineVertexInputStateCreateInfo vi{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};ia.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;VkViewport vp{0,0,float(width),float(height),0,1};VkRect2D sc{{0,0},{width,height}};VkPipelineViewportStateCreateInfo vs{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};vs.viewportCount=vs.scissorCount=1;vs.pViewports=&vp;vs.pScissors=&sc;VkPipelineRasterizationStateCreateInfo rs{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};rs.polygonMode=VK_POLYGON_MODE_FILL;rs.cullMode=VK_CULL_MODE_NONE;rs.lineWidth=1;VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};ms.rasterizationSamples=VK_SAMPLE_COUNT_1_BIT;std::array<VkPipelineColorBlendAttachmentState,layers>ba{};for(uint32_t i=0;i<layers;++i)ba[i].colorWriteMask=(*output_mask&(1u<<i))?15:0;VkPipelineColorBlendStateCreateInfo bs{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};bs.attachmentCount=layers;bs.pAttachments=ba.data();VkGraphicsPipelineCreateInfo gi{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};gi.stageCount=2;gi.pStages=stages.data();gi.pVertexInputState=&vi;gi.pInputAssemblyState=&ia;gi.pViewportState=&vs;gi.pRasterizationState=&rs;gi.pMultisampleState=&ms;gi.pColorBlendState=&bs;gi.layout=pl;gi.renderPass=rp;VkPipeline result;V(vkCreateGraphicsPipelines(device,VK_NULL_HANDLE,1,&gi,nullptr,&result));pipelines[key]=result;return result;};
 std::ifstream cases(argv[2]);Check(bool(cases),"cases manifest");std::string name,path,datafile;uint32_t spec,pattern,linear;uint64_t cases_run=0;bool textures_initialized=false;
 for(;cases>>name>>path>>datafile>>spec>>pattern>>linear;){auto data=Read(datafile);constexpr size_t input_bytes=256+4096+0x420+32*16;Check(data.size()==input_bytes,"case input length");size_t offset=0;std::memcpy(varyings.mapping,data.data()+offset,256);offset+=256;std::memcpy(constants.mapping,data.data()+offset,4096);offset+=4096;std::memcpy(shared.mapping,data.data()+offset,0x420);offset+=0x420;auto pipe=pipeline(path,spec);
 for(uint32_t i=0;i<slots;++i){sa[i].sampler=linear?linear_sampler:sampler;float base_color[4];std::memcpy(base_color,data.data()+offset+i*16,16);
  auto* pixels=reinterpret_cast<uint16_t*>(static_cast<uint8_t*>(texture_upload.mapping)+texture_offsets[i]);
  for(uint32_t level=0;level<textures[i].mip_levels;++level){uint32_t mip_width=std::max(1u,textures[i].width>>level),mip_height=std::max(1u,textures[i].height>>level);
  for(uint32_t y=0;y<mip_height;++y)for(uint32_t x=0;x<mip_width;++x){
   float c[4];std::memcpy(c,base_color,sizeof(c));float u=(float(x)+0.5f)/mip_width,v=(float(y)+0.5f)/mip_height;
   if(pattern){
    if(i==2){float edge=((x/7+y/5)%2)?0.75f:0.0f;c[0]+=u+edge;c[1]+=v;c[2]+=(u*v+edge);if((pattern&2)&&x==width/2)c[0]+=24.0f;}
    if(i==1){c[0]*=(x<width/2)?0.7f:1.1f;}
    if(i==3){c[0]+=u*0.1f;c[2]+=v*0.1f;}
    if(i==5){c[0]=float((x*1664525u+y*1013904223u+pattern*747796405u)&65535u)/65535.0f;}
    if(i==6&&(pattern&4)){c[2]=(u>0.32f&&u<0.68f&&v>0.2f&&v<0.8f)?1.0f:0.0f;}
   }
   if(i==2){c[0]+=float(level)*0.125f;c[1]+=float(level)*0.0625f;}
   for(uint32_t channel=0;channel<4;++channel)pixels[(size_t(y)*mip_width+x)*4+channel]=std::bit_cast<uint16_t>(static_cast<_Float16>(c[channel]));
  }
  pixels+=size_t(mip_width)*mip_height*4;
  }
 }
 vkUpdateDescriptorSets(device,1,&writes[1],0,nullptr);
 V(vkResetCommandBuffer(cb,0));VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};V(vkBeginCommandBuffer(cb,&bi));vkCmdResetQueryPool(cb,timestamps,0,repeats*2);
 for(uint32_t i=0;i<slots;++i){VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.srcAccessMask=textures_initialized?VK_ACCESS_SHADER_READ_BIT:0;b.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b.oldLayout=textures_initialized?VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL:VK_IMAGE_LAYOUT_UNDEFINED;b.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.srcQueueFamilyIndex=b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=textures[i].handle;b.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,textures[i].mip_levels,0,1};vkCmdPipelineBarrier(cb,textures_initialized?VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT:VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b);VkBufferImageCopy upload{};upload.bufferOffset=texture_offsets[i];for(uint32_t level=0;level<textures[i].mip_levels;++level){upload.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,level,0,1};upload.imageExtent={std::max(1u,textures[i].width>>level),std::max(1u,textures[i].height>>level),1};vkCmdCopyBufferToImage(cb,texture_upload.handle,b.image,b.newLayout,1,&upload);upload.bufferOffset+=size_t(upload.imageExtent.width)*upload.imageExtent.height*8;}b.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;b.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;b.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;vkCmdPipelineBarrier(cb,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&b);}
 textures_initialized=true;std::array<VkClearValue,layers>clears{};for(auto&c:clears)c.color={{-17,-17,-17,-17}};VkRenderPassBeginInfo begin{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};begin.renderPass=rp;begin.framebuffer=fb;begin.renderArea.extent={width,height};begin.clearValueCount=layers;begin.pClearValues=clears.data();for(uint32_t iteration=0;iteration<repeats;++iteration){vkCmdWriteTimestamp(cb,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,timestamps,iteration*2);vkCmdBeginRenderPass(cb,&begin,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(cb,VK_PIPELINE_BIND_POINT_GRAPHICS,pipe);vkCmdBindDescriptorSets(cb,VK_PIPELINE_BIND_POINT_GRAPHICS,pl,0,uint32_t(sets.size()),sets.data(),0,nullptr);vkCmdPushConstants(cb,pl,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,24,push.data());vkCmdDraw(cb,3,1,0,0);vkCmdEndRenderPass(cb);vkCmdWriteTimestamp(cb,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,timestamps,iteration*2+1);}
 for(uint32_t i=0;i<layers;++i){VkBufferImageCopy c{};c.bufferOffset=i*width*height*16;c.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};c.imageExtent={width,height,1};vkCmdCopyImageToBuffer(cb,targets[i].handle,VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,readback.handle,1,&c);}VkBufferMemoryBarrier barrier{VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER};barrier.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;barrier.dstAccessMask=VK_ACCESS_HOST_READ_BIT;barrier.srcQueueFamilyIndex=barrier.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;barrier.buffer=readback.handle;barrier.size=VK_WHOLE_SIZE;vkCmdPipelineBarrier(cb,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,0,nullptr,1,&barrier,0,nullptr);V(vkEndCommandBuffer(cb));VkSubmitInfo submit{VK_STRUCTURE_TYPE_SUBMIT_INFO};submit.commandBufferCount=1;submit.pCommandBuffers=&cb;V(vkQueueSubmit(queue,1,&submit,VK_NULL_HANDLE));V(vkQueueWaitIdle(queue));
 std::vector<uint64_t> ticks(repeats*2);V(vkGetQueryPoolResults(device,timestamps,0,repeats*2,ticks.size()*sizeof(uint64_t),ticks.data(),sizeof(uint64_t),VK_QUERY_RESULT_64_BIT|VK_QUERY_RESULT_WAIT_BIT));
 for(uint32_t i=0;i<repeats;++i)std::cout<<"TIMING "<<name<<" iteration="<<i<<" begin="<<ticks[i*2]<<" end="<<ticks[i*2+1]<<" period_ns="<<props.limits.timestampPeriod<<" bits="<<qp[family].timestampValidBits<<"\n";
 auto* values=(float*)readback.mapping;uint64_t bad=0,covered=0;for(size_t i=0;i<width*height*4*layers;++i)bad+=!std::isfinite(values[i]);for(size_t i=0;i<width*height;++i)covered+=values[i*4]!=-17.0f;if(!std::getenv("REX_POSTFX_REPLAY_NO_READBACK_FILE")){std::ofstream raw(output/(name+".rgba32f"),std::ios::binary);raw.write((char*)values,width*height*16*layers);Check(bool(raw),"result write");}std::cout<<"RESULT "<<name<<" bad="<<bad<<" covered="<<covered<<" first=";for(uint32_t i=0;i<4*layers;++i)std::cout<<(i?",":"")<<values[(i/4)*width*height*4+i%4];std::cout<<'\n';++cases_run;}
 V(vkDeviceWaitIdle(device));for(auto&[k,p]:pipelines)vkDestroyPipeline(device,p,nullptr);for(auto m:modules)vkDestroyShaderModule(device,m,nullptr);vkDestroyCommandPool(device,pool,nullptr);vkDestroyFramebuffer(device,fb,nullptr);vkDestroyRenderPass(device,rp,nullptr);vkDestroyPipelineLayout(device,pl,nullptr);vkDestroyDescriptorPool(device,dp,nullptr);for(auto l:layouts)vkDestroyDescriptorSetLayout(device,l,nullptr);vkDestroySampler(device,sampler,nullptr);vkDestroySampler(device,linear_sampler,nullptr);vkDestroyQueryPool(device,timestamps,nullptr);for(auto&i:images){vkDestroyImageView(device,i.view,nullptr);vkDestroyImage(device,i.handle,nullptr);vkFreeMemory(device,i.memory,nullptr);}for(auto&b:buffers){vkUnmapMemory(device,b.memory);vkDestroyBuffer(device,b.handle,nullptr);vkFreeMemory(device,b.memory,nullptr);}vkDestroyDevice(device,nullptr);vkDestroyInstance(instance,nullptr);std::cout<<"COMPLETE cases="<<cases_run<<'\n';return 0;
}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
