#!/usr/bin/env python3
"""Generate lossless native assets from the pinned FusionFix references."""
from pathlib import Path
import hashlib
import struct

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / 'LibertyRecompLib/postfx/fusion_modern_reference'
OUTPUT = ROOT / 'glue/rexglue-sdk-main/include/rex/graphics/gta4_native'


def joaat(value):
    result = 0
    for byte in value.lower().encode('ascii'):
        result = (result + byte) & 0xffffffff
        result = (result + (result << 10)) & 0xffffffff
        result ^= result >> 6
    result = (result + (result << 3)) & 0xffffffff
    result ^= result >> 11
    return (result + (result << 15)) & 0xffffffff


def float_literal(value):
    text = format(float(value), '.9g')
    if '.' not in text and 'e' not in text:
        text += '.0'
    return text + 'f'


def main():
    dds = (REFERENCE / 'Frostbite_Custom_Hue_Preserve.dds').read_bytes()
    assert struct.unpack_from('<II', dds, 12) == (32, 1024)
    payload = dds[128:]
    assert hashlib.sha256(payload).hexdigest() == '84e9f4ca7e876f9ed490212546a12bfa74286e8a3707ba04dd9d011d3f0ef153'
    words = struct.unpack('<32768I', payload)
    (OUTPUT / 'fusion_tone_lut.h').write_text(
        '// Generated by tools/generate_modern_shader_assets.py; BGRA8 UNORM, no sRGB decode.\n'
        '#pragma once\n#include <array>\n#include <cstdint>\n'
        'namespace rex::graphics::gta4_native {\n'
        'inline constexpr std::array<uint32_t, 32768> kFusionToneLut = {\n' +
        ''.join('  ' + ', '.join(f'0x{x:08X}u' for x in words[i:i+8]) + ',\n' for i in range(0, len(words), 8)) + '};\n}\n')
    rows = []
    for line in (REFERENCE / 'timecycext.dat').read_text().splitlines():
        line = line.split('//')[0].strip()
        if line:
            values = line.split()
            assert len(values) == 6
            rows.append(values[:5])
    assert len(rows) == 9 * 11
    modifiers = []
    for line in (REFERENCE / 'timecyclemodifiersext.dat').read_text().splitlines():
        line = line.split('//')[0].strip()
        if line:
            values = line.split()
            assert len(values) == 7
            modifiers.append((joaat(values[0]), values[1:6]))
    assert len({key for key, _ in modifiers}) == len(modifiers)
    (OUTPUT / 'fusion_timecycle_data.inc').write_text(
        '// Generated by tools/generate_modern_shader_assets.py. Columns: density, falloff, altitude, power, shafts.\n'
        'inline constexpr std::array<FusionTimecycle, 99> kFusionTimecycles = {{\n' +
        ''.join('  {{' + ', '.join(map(float_literal, row)) + '}},\n' for row in rows) + '}};\n'
        'struct FusionModifier { uint32_t hash; FusionTimecycle values; };\n'
        f'inline constexpr std::array<FusionModifier, {len(modifiers)}> kFusionModifiers = {{{{\n' +
        ''.join(f'  {{0x{key:08X}u, {{{{' + ', '.join(map(float_literal, values)) + '}}},\n' for key, values in sorted(modifiers)) + '}};\n')


if __name__ == '__main__':
    main()
