#!/usr/bin/env python3
"""Derive narrow streaming hooks from pinned, compiled PPC translation units."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / 'generated'
OUTPUT = ROOT / 'src/gta4_streaming_guest.inc'
SOURCES = {
    'sub_821D8848': (5, 'b186dcb19e0df64d253808b55e10469e58b30d0c2a73c6053b7fde5b7d97387e'),
    'sub_825132D0': (33, '1b41bef76f16ae62b8ec60235bfc46cfbd87f46d225509ecab533676884fc9a9'),
}
HEADER = '''// Derived by tools/derive_streaming_hooks.py --write.
// Full reviewed generated PPC; narrowly scoped preload and ranking substitutions.
// No generated source is modified. Do not edit this file manually.

'''


def extract(text: str, name: str) -> str:
    marker = f'DEFINE_REX_FUNC({name}) {{'
    if text.count(marker) != 1:
        raise ValueError(f'{name}: expected one compiled definition')
    start = text.index(marker)
    end = text.find('\nDEFINE_REX_FUNC(', start + len(marker))
    return text[start:end if end >= 0 else len(text)].rstrip() + '\n'


def replace_once(text: str, old: str, new: str) -> str:
    if text.count(old) != 1:
        raise ValueError(f'Expected one substitution site: {old!r}; found {text.count(old)}')
    return text.replace(old, new, 1)


def originals() -> dict[str, str]:
    result = {}
    for name, (unit, expected_hash) in SOURCES.items():
        body = extract((GENERATED / f'gta4_recomp.{unit}.cpp').read_text(), name)
        actual = hashlib.sha256(body.encode()).hexdigest()
        if actual != expected_hash:
            raise ValueError(f'{name}: compiled source changed ({actual}); review before updating the pin')
        result[name] = body
    return result


# Retain the interface used by the existing differential-test runner.
SPECS = tuple((name, unit, digest) for name, (unit, digest) in SOURCES.items())

def original(name: str, unit: int, expected_hash: str) -> str:
    body = extract((GENERATED / f'gta4_recomp.{unit}.cpp').read_text(), name)
    actual = hashlib.sha256(body.encode()).hexdigest()
    if actual != expected_hash:
        raise ValueError(f'{name}: source changed ({actual}); review required')
    return body


def derive(bodies: dict[str, str]) -> str:
    preload = replace_once(bodies['sub_821D8848'], 'DEFINE_REX_FUNC(sub_821D8848) {', '''static void ClassifyWorldEntityImpl(PPCContext& ctx, uint8_t* base) {''')
    preload = replace_once(preload,
        '\ttemp.u32 = REX_LOAD_U32(ctx.r11.u32 + 2604);\n\tctx.f0.f64 = double(temp.f32);',
        '\ttemp.u32 = REX_LOAD_U32(ctx.r11.u32 + 2604);\n'
        '\tctx.f0.f64 = EntityPreloadMargin(base, ctx.r31.u32, ctx.r29.u32,\n'
        '                                          ctx.f27.f64, ctx.f31.f64, temp.f32);')
    preload += '''
extern "C" void sub_821D8848(PPCContext& ctx, uint8_t* base) {
  const uint32_t entity = ctx.r3.u32;
  const uint32_t view = ctx.r8.u32;
  const double distance = ctx.f1.f64;
  if (!config.modern || !world.entity) {
    __imp__sub_821D8848(ctx, base);
  } else {
    ClassifyWorldEntityImpl(ctx, base);
  }
  ObserveClassification(base, entity, view, distance, ctx.r3.u32);
}
'''
    queue = replace_once(bodies['sub_825132D0'], 'DEFINE_REX_FUNC(sub_825132D0) {', '''extern "C" void sub_825132D0(PPCContext& ctx, uint8_t* base) {
  if (!DeadlineOrderEnabled(base, ctx.r3.u32)) {
    __imp__sub_825132D0(ctx, base);
    return;
  }
  uint64_t candidate_rank = UINT64_MAX;
  uint64_t minimum_rank = UINT64_MAX;
  uint64_t selected_rank = UINT64_MAX;''')
    queue = replace_once(queue, 'loc_82513620:\n', 'loc_82513620:\n  candidate_rank = QueueRank(ctx.r28.u32);\n')
    for register, rank in [('r18', 'minimum_rank'), ('r19', 'selected_rank')]:
        queue = replace_once(queue,
            f'\tctx.cr6.compare<uint32_t>(ctx.r11.u32, ctx.{register}.u32, ctx.xer);',
            f'\tctx.cr6.compare<uint32_t>(RankBefore(candidate_rank, ctx.r11.u32, {rank}, ctx.{register}.u32) ? 0 : 1, 1, ctx.xer);')
        queue = replace_once(queue, f'\tctx.{register}.u64 = ctx.r11.u64;\n',
            f'\tctx.{register}.u64 = ctx.r11.u64;\n  {rank} = candidate_rank;\n')
    queue = replace_once(queue,
        '\tctx.cr6.compare<uint32_t>(ctx.r11.u32, ctx.r15.u32, ctx.xer);',
        '\t// No seek-head cursor gate on the host deadline-ordered path.\n'
        '  ctx.cr6.compare<uint32_t>(1, 0, ctx.xer);')
    return HEADER + preload + '\n' + queue


def fixture_sources(bodies: dict[str, str], destination: Path) -> None:
    """Extract real baseline code and register save/restore helpers for differential tests."""
    required = set()
    for body in bodies.values():
        required.update(re.findall(r'\b(__\w+)\(ctx, base\);', body))
    helpers: dict[str, str] = {}
    for path in sorted(GENERATED.glob('gta4_recomp.*.cpp')):
        text = path.read_text()
        for name in required - helpers.keys():
            if f'DEFINE_REX_FUNC({name}) {{' in text:
                helpers[name] = extract(text, name)
    missing = required - helpers.keys()
    if missing:
        raise ValueError(f'Missing compiled register helpers: {sorted(missing)}')
    content = '// Test baseline extracted from compiled sources; no behavioural reconstruction.\n'
    for name in sorted(helpers):
        content += replace_once(helpers[name], f'DEFINE_REX_FUNC({name}) {{',
                                f'extern "C" void {name}(PPCContext& ctx, uint8_t* base) {{') + '\n'
    for name, body in bodies.items():
        body = replace_once(body, f'DEFINE_REX_FUNC({name}) {{',
                            f'extern "C" void __imp__{name}(PPCContext& ctx, uint8_t* base) {{')
        # A baseline recursive call must stay entirely on the baseline path.
        body = body.replace(f'\t{name}(ctx, base);', f'\t__imp__{name}(ctx, base);')
        content += body + '\n'
    destination.mkdir(parents=True, exist_ok=True)
    (destination / 'streaming_original_fixture.inc').write_text(content)


def verify_host_shutdown_contract() -> None:
    """Check production ordering; runtime queue tests exercise the drain primitive."""
    source = (ROOT.parent/'src/system/kernel_state.cpp').read_text()
    shutdown = source.split('void KernelState::TerminateTitle() {', 1)[1].split('\n}\n', 1)[0]
    markers = ('dispatch_accepting_ = false;', 'host_io_accepting_ = false;',
               'WaitForHostTasks();', 'terminating_title_.store(true, std::memory_order_release);',
               'SignalAllWaitableObjects();')
    positions = [shutdown.index(marker) for marker in markers]
    if positions != sorted(positions):
        raise ValueError('Host admission must stop and drain before cooperative guest exit')
    restart = source.split('void KernelState::StartHostIoWorkers() {', 1)[1].split('\n}\n', 1)[0]
    retained = restart.split('if (host_io_queue_) {', 1)[1].split('}', 1)[0]
    if 'host_io_accepting_ = true;' not in retained:
        raise ValueError('Retained I/O workers must reopen admission for the new title')
    print('PASS: host admission fence, drain-before-exit and worker reuse contract')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    parser.add_argument('--fixture-output', type=Path)
    args = parser.parse_args()
    verify_host_shutdown_contract()
    bodies = originals()
    derived = derive(bodies)
    if args.write:
        if not OUTPUT.exists() or OUTPUT.read_text() != derived:
            OUTPUT.write_text(derived)
    elif not OUTPUT.exists() or OUTPUT.read_text() != derived:
        raise ValueError(f'{OUTPUT}: does not match pinned derivation; run --write after review')
    if args.fixture_output:
        fixture_sources(bodies, args.fixture_output)
    print('PASS: pinned compiled sources and exact streaming substitutions verified')
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError) as error:
        print(f'FAIL: {error}', file=sys.stderr)
        sys.exit(1)
